// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozzhyzzgiqpyvygqfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvenpoeXp6Z2lxcHl2eWdxZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mzk4MTIsImV4cCI6MjA3MTIxNTgxMn0.U00ilDj9spzT2inZjFduZhvg0I1ecyao93Qk3rkNTEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});